# Explore here

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [74]:
main_df = pd.read_csv('https://raw.githubusercontent.com/4GeeksAcademy/naive-bayes-project-tutorial/main/playstore_reviews.csv')

In [3]:
main_df.head()

package_name                                             review  \
0  com.facebook.katana   privacy at least put some option appear offli...   
1  com.facebook.katana   messenger issues ever since the last update, ...   
2  com.facebook.katana   profile any time my wife or anybody has more ...   
3  com.facebook.katana   the new features suck for those of us who don...   
4  com.facebook.katana   forced reload on uploading pic on replying co...   

   polarity  
0         0  
1         0  
2         0  
3         0  
4         0

In [75]:
main_df['review'] = main_df['review'].str.strip()

In [76]:
main_df['review']

0      privacy at least put some option appear offlin...
1      messenger issues ever since the last update, i...
2      profile any time my wife or anybody has more t...
3      the new features suck for those of us who don'...
4      forced reload on uploading pic on replying com...
                             ...                        
886    loved it i loooooooooooooovvved it because it ...
887    all time legendary game the birthday party lev...
888    ads are way to heavy listen to the bad reviews...
889    fun works perfectly well. ads aren't as annoyi...
890    they're everywhere i see angry birds everywher...
Name: review, Length: 891, dtype: object

In [5]:
main_df['review'] = main_df['review'].str.strip().str.lower()

In [77]:
text = "Hello, World! How's it going"

In [79]:
import string

In [81]:
translator = str.maketrans('', '', string.punctuation)
cleaned_text = text.translate(translator)
print(cleaned_text)

Hello World Hows it going


In [6]:
main_df['review']

0      privacy at least put some option appear offlin...
1      messenger issues ever since the last update, i...
2      profile any time my wife or anybody has more t...
3      the new features suck for those of us who don'...
4      forced reload on uploading pic on replying com...
                             ...                        
886    loved it i loooooooooooooovvved it because it ...
887    all time legendary game the birthday party lev...
888    ads are way to heavy listen to the bad reviews...
889    fun works perfectly well. ads aren't as annoyi...
890    they're everywhere i see angry birds everywher...
Name: review, Length: 891, dtype: object

In [8]:
from sklearn.feature_extraction.text import CountVectorizer

In [40]:
vec_model = CountVectorizer(stop_words='english', min_df=10)

In [68]:
vec_model

CountVectorizer(min_df=10, stop_words='english')

In [41]:
X = vec_model.fit_transform(main_df['review'])

In [73]:
X

<891x363 sparse matrix of type '<class 'numpy.int64'>'
	with 8807 stored elements in Compressed Sparse Row format>

In [72]:
print(X.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [71]:
vec_model.get_feature_names_out()

array(['10', 'ability', 'able', 'access', 'account', 'actually', 'ad',
       'add', 'ads', 'allow', 'amazing', 'android', 'angry', 'annoying',
       'anymore', 'app', 'appear', 'application', 'apps', 'automatically',
       'available', 'away', 'awesome', 'background', 'bad', 'best',
       'better', 'big', 'birds', 'bit', 'boosters', 'box', 'browser',
       'browsers', 'browsing', 'bug', 'bugs', 'button', 'buy', 'change',
       'changed', 'chat', 'check', 'chrome', 'click', 'close', 'come',
       'company', 'connect', 'connected', 'connection', 'constantly',
       'contact', 'contacts', 'cool', 'couldn', 'crashes', 'data', 'day',
       'days', 'default', 'desktop', 'developers', 'device', 'devices',
       'did', 'didn', 'different', 'directly', 'does', 'doesn', 'doing',
       'don', 'dont', 'download', 'downloading', 'drop', 'dropbox',
       'easy', 'edit', 'end', 'english', 'error', 'especially',
       'evernote', 'excellent', 'facebook', 'far', 'fast', 'favorite',
       

In [42]:

y = main_df['polarity']

In [24]:
from sklearn.model_selection import train_test_split

In [43]:
X_train, X_test, y_train, y_test = train_test_split(X,y)

In [16]:
from sklearn.naive_bayes import MultinomialNB

In [17]:
nb_model = MultinomialNB()

In [18]:
nb_model

MultinomialNB()

In [44]:
nb_model.fit(X_train, y_train)

MultinomialNB()

In [45]:
y_train_preds = nb_model.predict(X_train)

In [46]:
y_train_preds

array([1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,

In [47]:
y_test_preds = nb_model.predict(X_test)

In [48]:
y_test_preds

array([1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0])

In [37]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [66]:
def score_maker(model, X_train, X_test, y_train, y_test):
    print(f'training accuracy is {accuracy_score(y_train, y_train_preds)}')
    print(f'testing accuracy is {accuracy_score(y_test, y_test_preds)}')

    print(f'training confusion matrix is {confusion_matrix(y_train, y_train_preds)}')
    print(f'testing confusion matrix is {confusion_matrix(y_test, y_test_preds)}')

    print('the training classfication report is\n')
    print(f'{classification_report(y_train, y_train_preds)}')
    print('testing classfication report is\n')
    print(f'{confusion_matrix(y_test, y_test_preds)}')

In [67]:
score_maker(nb_model, X_train, X_test, y_train, y_test )

training accuracy is 0.8622754491017964
testing accuracy is 0.7892376681614349
training confusion matrix is [[399  45]
 [ 47 177]]
testing confusion matrix is [[122  18]
 [ 29  54]]
the training classfication report is

              precision    recall  f1-score   support

           0       0.89      0.90      0.90       444
           1       0.80      0.79      0.79       224

    accuracy                           0.86       668
   macro avg       0.85      0.84      0.85       668
weighted avg       0.86      0.86      0.86       668

testing classfication report is

[[122  18]
 [ 29  54]]
